Hello: Hola

Novetats: Afegida traducció missatges de registre.<br/>Nom de moneda curt a detalls del vol.

Welcome nom@Text: Benvingut/da #{nom}, has entrat.

Yes: Sí
No: No

UserEmail: Adreça electrònica
UserVeto: Veto
UserInfoAdminViewTitle: Detalls de l'usuari
UserInfoAdminLlistarArticlesTitle: Articles de l'usuari
UserInfoLlistar_articles: Articles

UserInfoTitle: El meu perfil

UserInfoNom: Nom
UserInfoCognoms: Cognoms
UserInfoAdreça: Adreça
UserInfoCodiPostal: Codi postal
UserInfoPoblació: Ciutat
UserInfoPaís: País
UserInfoIdioma: Idioma per a la web
UserInfoTelèfon: Telèfon

UserInfo_GrupNom: Nom
UserInfo_GrupAdreça: Adreça
UserInfo_GrupComm: Comunicació
UserInfo_GrupAltres: Altres


Submit: enviar
DeleteArt: anul·lar article

UserInfoAdminVisitaCanviarVeto: Canviar veto

IdiomaEN: Anglès
IdiomaCA: Català

UsrInfoHasBeenUpdated: El perfil ha estat actualitzat
PleaseCorrect: Si us plau, corregiu 

CtrySpain:Espanya
CtryUK:Regne unit
CtryFrance: França
CtryGermany:Alemanya

Def_login: Inici de sessió
Def_logout: Tancar la sessió
Def_userInfo: El meu perfil
Def_addFlight: Afegir vol
Def_myFlights: Els meus vols
Def_allFlights: Tots els vols
Def_othersFlights: Vols dels altres
Def_searchForFlights: Cercar vols
Def_searchForOthersFlights: Cercar vols dels altres
Def_mail: Correu
Def_findUsers: Cercar usuaris
Def_admin: Administració
Def_credits: Crèdits

Confirm: N'estàs segur?

Fnd_IDontHaveAnAccount:No tinc cap compte / Restablir la contrasenya

HistoryBack: Tornar

GlobalsTitle: Dades globals
Def_globals: Dades globals

FrmGlobalsComissió: Comissió (%)
FrmGlobalsAdmin: Administrador

GlobalsComissió: Comissió
GlobalsAdmins: Administradors
Globals_ErrComissióIlegal: Valor ha d'ésser > 0
GlobalsHasBeenUpdated: Dades globals actualitzades

UserArtPreu: Preu
UserArtPreuDeVenda: Preu de venda
UserArtMoneda: Moneda
UserArtÉsPreuNegociable: Preu és negociable
UserArtData: Data
UserArtComentaris: Comentaris
UserArtTipusArt: Tipus d'article
UserArtEstat: Estat

TipArtVol: Vol
TipArtAllotjament: Allotjament

UserVolOrigenPaís: País d'origen
UserVolOrigenPoblació: Població
UserVolOrigenAeroport: Aeroport

UserVolDestíPaís: País de destí
UserVolDestíPoblació: Població
UserVolDestíAeroport: Aeroport

UserVolAnada: Anada
UserVolTornada: Tornada
UserVolDataAnada: Data de partida
UserVolNumVolAnada: Número de vol
UserVolDataTornada: Data de retorn
UserVolNumVolTornada: Número de vol
UserVolLíniaAèria: Línia aèria
UserVolNumReserva: Reserva num.
UserVolWebOnVaFerLaReserva: Web o lloc on va fer la reserva
UserVolNombreDeSeients: Nombre de places

LegendOrigen: Origen
LegendDestí: Destí
LegendAnada: Anada
LegendTornada: Tornada
LegendDetalls: Detalls

UserMsgPosted: Dia i hora
UserMsgFrom: De part de
UserMsgAssumpte: Assumpte
UserMsgCos: Cos
UserMsgLlegit: Llegit
UserMsgUrgent: Urgent

UserMsgLlegitSí:
UserMsgLlegitNo: Nou

UserAddFlightTitle: Afegir vol
UserEditFlightTitle: Modificar vol
UserVisitFlightTitle: Detalls del vol
UserViewMsgTitle: Detalls del missatge
UserListMsgTitle: Correu

Edit: modificar
BotòEnviarMsgInterès: Enviar missatge d'interès


UserVol_HasBeenAdded: El vol ha estat afegit
UserVol_HasBeenUpdated: El vol ha estat actualitzat
UserVol_HasBeenDeleted: El vol ha estat desactivat

InterèsEnviat: El missatge d'interès sobre el Vol ha estat enviat

UserVol_ErrOrigenIgualADEstí: Els camps Origen i Destinació han d'ésser diferents
UserVol_ErrDataAnadaÉsEnElPassat: Data d'anada no pot ser en el passat
UserVol_ErrDataAnadaÉsAnteriorADataTornada: Data de tornada no pot ser anterior a data d'anada
UserVol_ErrMancaNumVolTornada: A la tornada hi manca el num. de vol
UserVol_ErrNombreDeSeientsNoPositiu: Nombre de places ha d'ésser positiu

UserListMyFlightsTitle: Els meus vols
UserListOthersFlightsTitle: Vols dels altres
UserListAllFlightsTitle: Tots els vols

Empty: buit
Unknown: desconegut

ListFlightsFrom: De
ListFlightsTo: A

FlightSearchTitle: Cercar vols

Idiomes: Idiomes

NavPrimer: Primer
NavSegüent: Següent
NavAnterior: Anterior

RecentVols: Vols recents
Detalls: Detalls
BotóVisitaDetallsArticle: Detalls de l'article relacionat

ErrRequeixPerfilUsuari: Cal que ompli el perfil de l'usuari
TensCorreuALaBustiaDelCompte: Tens correu a la web de La Revenda

EstArt_Exposat: Exposat
EstArt_Anuŀlat: Anuŀlat
EstArt_Compromès: Reservat
EstArt_Venut: Venut